### ISSUE TITLE
Error when checking for alerts after spider/passive scan

### ISSUE THREAD

**Issue by gigadatChrisB** [yukisov/php-owasp-zap-v2#5]
Hello,

I am running some passive scans on a site using the php library and am running into an error when executing the alerts method in the core section.

`$alerts = $zap->core->alerts($target, "", "");`

It is returning the following error:

reset(): Argument #1 ($array) must be of type array, null given

However, when I run the same request through the ZAP UI, It works fine and I get the results that I am looking for. This issue is sort of intermittent. It seems that if I restart the ZAP interface (either UI or command line) it will mostly work on the first attempt, but will fail on subsequent attempts.

I have not been able to determine the cause of this issue. Any help would be greatly appreciated.

**Comment by jotefer** [comment]
Call `alerts` method without second and third param like `$alerts = $zap->core->alerts($target);` since in source code is check against NULL value, there might be a bug in there. Or try to call it with $start and $end param to check if it returns anything for first 10 results `$alerts = $zap->core->alerts($target, 1, 10);`

**Comment by gigadatChrisB** [comment]
@jotefer thank you for the reply. I will try that and respond with the results. 
Can you tell me if this package will be updated with the latest API updates? Is anyone still maintaining this project? It seems there are a number of new API requests that are missing from the package including the new Reports section.

**Comment by gigadatChrisB** [comment]
Just to follow up here, running with single argument does not seem to work. However, running and specifying start and end parameters seems to work consistently.

@jotefer thanks for the recommendations.

**Comment by jotefer** [comment]
Glad to hear it helped @gigadatChrisB 
I think the problem is that zap found to many alerts, and PHP request is timed out. I had this problem once, and fetching alerts in chunks was the only solution i got.
As for the package i don't think its maintain anymore. However adding new APIs should be a fairly easy task to do.
